name: GCC

on: push

jobs:
  gcc:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        version: [9, 10, 11, 12, 13, 14]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake g++-${{ matrix.version }} libxml2-dev pkg-config zlib1g-dev
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j4
          ctest -V
      - name: Build with GNU GCC ${{ matrix.version }} - static linking
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build-static
          cd build-static
          cmake .. -DENABLE_STATIC_LINKING=ON -DENABLE_LTO=ON
          cmake --build . -j2
        # Only do static build on latest version in the matrix.
        if: matrix.version == 14
