name: MSYS2

on: push

jobs:
  msys2_mingw64:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          persist-credentials: false
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-libiconv
      - name: Build
        run: |
          export MSYSTEM=MINGW64
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          mkdir build
          cd build
          cmake ../
          cmake --build . -j2
          ctest -V
      - name: Build statically linked
        run: |
          export MSYSTEM=MINGW64
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          mkdir build-static
          cd build-static
          cmake -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON ../
          cmake --build . -j2
      - name: Collect statically linked artifacts
        run: |
          export MSYSTEM=MINGW64
          cd "$GITHUB_WORKSPACE"
          mkdir -p "$GITHUB_WORKSPACE"/artifacts
          # binary file
          cp build-static/htmlify/htmlify.exe artifacts/
          # license + readme
          cp LICENSE artifacts/
          cp readme.md artifacts/
          # determine version
          VERSION=$(git describe --always)
          echo Version is $VERSION.
          mv artifacts htmlify-$VERSION
          "C:\Program Files\7-Zip\7z.exe" a -r htmlify_${VERSION}_win64.zip htmlify-$VERSION
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: htmlify-msys2-win64
          path: htmlify_*_win64.zip
          if-no-files-found: error
